name: Image Optimization

on:
  workflow_dispatch:
  
jobs:
  optimize-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick

    - name: Install jpegoptim
      run: sudo apt-get install -y jpegoptim

    - name: Install SVGO
      run: npm install -g svgo

    - name: Optimize Images
      run: |
        find images -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.svg" \) -exec mogrify -resize 50% {} \;
        find images -type f -name "*.jpg" -exec jpegoptim {} \;
        find images -type f -name "*.svg" -exec svgo {} \;

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Image Optimization🧹"
        git add images
        git commit -m "Optimize images"
        git push origin developer
